# Data-X Spring 2019: Homework 06 

## Name : Anirudh Chatty
## SID : 3034339104
## Course (IEOR 135/290) : IEOR 290

### Machine Learning



In this homework, you will do some exercises with prediction. We will cover these algorithms in class, but this is for you to have some hands on with these in scikit-learn. You can refer - https://github.com/ikhlaqsidhu/data-x/blob/master/05a-tools-predicition-titanic/titanic.ipynb

Display all your outputs.


In [1]:
import numpy as np
import pandas as pd

In [2]:
 # machine learning libraries
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import Perceptron
from sklearn.tree import DecisionTreeClassifier
import warnings
warnings.filterwarnings('ignore')



__ 1. Read __`diabetesdata.csv`__ file into a pandas dataframe. 
About the data: __

1. __TimesPregnant__: Number of times pregnant 
2. __glucoseLevel__: Plasma glucose concentration a 2 hours in an oral glucose tolerance test 
3. __BP__: Diastolic blood pressure (mm Hg)  
5. __insulin__: 2-Hour serum insulin (mu U/ml) 
6. __BMI__: Body mass index (weight in kg/(height in m)^2) 
7. __pedigree__: Diabetes pedigree function 
8. __Age__: Age (years) 
9. __IsDiabetic__: 0 if not diabetic or 1 if diabetic) 








In [3]:
#Read data & print the head

data = pd.read_csv("diabetesdata.csv")
data.head()

TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  IsDiabetic
0              6         148.0  72        0  33.6     0.627  50.0           1
1              1           NaN  66        0  26.6     0.351  31.0           0
2              8         183.0  64        0  23.3     0.672   NaN           1
3              1           NaN  66       94  28.1     0.167  21.0           0
4              0         137.0  40      168  43.1     2.288  33.0           1

**2. Calculate the percentage of Null values in each column and display it. **

In [4]:
Null_percentage = data.isna().sum()/len(data)
Null_percentage

TimesPregnant    0.000000
glucoseLevel     0.044271
BP               0.000000
insulin          0.000000
BMI              0.000000
Pedigree         0.000000
Age              0.042969
IsDiabetic       0.000000
dtype: float64

**3. Split __`data`__  into  __`train_df`__ and __`test_df`__  with 15% as test.**


In [5]:
#Importing the package for splitting
from sklearn.model_selection import train_test_split

#Splitting the dataset
train_df,test_df = train_test_split(data,test_size = 0.15)

train_df


TimesPregnant  glucoseLevel   BP  insulin   BMI  Pedigree   Age  \
40               3         180.0   64       70  34.0     0.271  26.0   
177              0         129.0  110      130  67.1     0.319  26.0   
600              1         108.0   88        0  27.1     0.400  24.0   
162              0         114.0   80      285  44.2     0.167  27.0   
647              0         179.0   50      159  37.8     0.455  22.0   
155              7         152.0   88        0  50.0     0.337  36.0   
727              0         141.0   84        0  32.4     0.433   NaN   
226              0         101.0   76        0  35.7     0.198  26.0   
373              2         105.0   58       94  34.9     0.225  25.0   
95               6         144.0   72      228  33.9     0.255  40.0   
399              3         193.0   70        0  34.9     0.241  25.0   
729              2          92.0   52        0  30.1     0.141  22.0   
11              10         168.0   74        0  38.0     0.537  34.0   
372              0          84.0   64       66  35.8     0.545  21.0   
197              3         107.0   62       48  22.9     0.678  23.0   
575              1         119.0   44       63  35.5     0.280  25.0   
359              1         196.0   76      249  36.5     0.875  29.0   
511              0         139.0   62      210  22.1     0.207  21.0   
250              9         106.0   52        0  31.2     0.380  42.0   
346              1         139.0   46       83  28.7     0.654  22.0   
663              9         145.0   80      130  37.9     0.637  40.0   
713              0           NaN   58      291  26.4     0.352  21.0   
224              1         100.0   66       56  23.6     0.666  26.0   
394              4         158.0   78        0  32.9     0.803  31.0   
306             10         161.0   68      132  25.5     0.326  47.0   
38               2           NaN   68        0  38.2     0.503  27.0   
195              5         158.0   84      210  39.4     0.395  29.0   
464             10         115.0   98        0  24.0     1.022  34.0   
385              1         119.0   54       50  22.3     0.205  24.0   
42               7         106.0   92        0  22.7     0.235  48.0   
..             ...           ...  ...      ...   ...       ...   ...   
1                1           NaN   66        0  26.6     0.351  31.0   
420              1         119.0   88      170  45.3     0.507  26.0   
764              2         122.0   70        0  36.8     0.340  27.0   
726              1         116.0   78      180  36.1     0.496  25.0   
702              1         168.0   88        0  35.0     0.905  52.0   
435              0         141.0    0        0  42.4     0.205  29.0   
0                6         148.0   72        0  33.6     0.627  50.0   
631              0         102.0   78       90  34.5     0.238  24.0   
407              0         101.0   62        0  21.9     0.336  25.0   
687              1         107.0   50        0  28.3     0.181  29.0   
80               3         113.0   44        0  22.4     0.140  22.0   
589              0          73.0    0        0  21.1     0.342  25.0   
479              4         132.0   86        0  28.0     0.419  63.0   
579              2         197.0   70        0  34.7     0.575  62.0   
732              2         174.0   88      120  44.5     0.646  24.0   
447              0          95.0   80       92  36.5     0.330  26.0   
193             11         135.0    0        0  52.3     0.578  40.0   
715              7           NaN   50      392  33.9     0.826  34.0   
405              2         123.0   48      165  42.1     0.520  26.0   
127              1         118.0   58       94  33.3     0.261  23.0   
472              0         119.0   66        0  38.8     0.259  22.0   
453              2         119.0    0        0  19.6     0.832  72.0   
21               8          99.0   84        0  35.4     0.388  50.0   
121              6         111.0   64        

In [6]:
test_df

TimesPregnant  glucoseLevel   BP  insulin   BMI  Pedigree   Age  \
245              9         184.0   85        0  30.0     1.213  49.0   
10               4         110.0   92        0  37.6     0.191   NaN   
343              5         122.0   86        0  34.7     0.290  33.0   
91               4         123.0   80      176  32.0     0.443  34.0   
546              5         187.0   76      207  43.6     1.034  53.0   
728              2           NaN   88        0  22.9     0.326  22.0   
166              3         148.0   66        0  32.5     0.256  22.0   
418              1          83.0   68        0  18.2     0.624  27.0   
710              3         158.0   64      387  31.2     0.295  24.0   
367              0         101.0   64        0  21.0     0.252  21.0   
238              9         164.0   84        0  30.8     0.831  32.0   
234              3          74.0   68       45  29.7     0.293  23.0   
189              5         139.0   80      160  31.6     0.361  25.0   
601              6          96.0    0        0  23.7     0.190  28.0   
34              10         122.0   78        0  27.6     0.512   NaN   
7               10         115.0    0        0  35.3     0.134  29.0   
101              1         151.0   60        0  26.1     0.179  22.0   
181              0         119.0   64       92  34.9     0.725  23.0   
276              7         106.0   60        0  26.5     0.296  29.0   
344              8          95.0   72        0  36.8     0.485  57.0   
441              2          83.0   66       50  32.2     0.497  22.0   
114              7         160.0   54      175  30.5     0.588  39.0   
84               5         137.0  108        0  48.8     0.227  37.0   
438              1          97.0   70        0  18.2     0.147  21.0   
294              0         161.0   50        0  21.9     0.254  65.0   
304              3         150.0   76        0  21.0     0.207  37.0   
454              2         100.0   54      105  37.8     0.498  24.0   
305              2         120.0   76      105  39.7     0.215  29.0   
378              4         156.0   75        0  48.3     0.238  32.0   
123              5         132.0   80        0  26.8     0.186  69.0   
..             ...           ...  ...      ...   ...       ...   ...   
109              0          95.0   85       36  37.4     0.247  24.0   
752              3         108.0   62        0  26.0     0.223  25.0   
206              8         196.0   76      280  37.5     0.605  57.0   
443              8         108.0   70        0  30.5     0.955  33.0   
291              0         107.0   62       74  36.6     0.757  25.0   
89               1         107.0   68        0  26.5     0.165  24.0   
566              1          99.0   72       18  38.6     0.412  21.0   
708              9           NaN   78        0  32.8     0.148  45.0   
311              0         106.0   70      148  39.4     0.605  22.0   
347              3         116.0    0        0  23.5     0.187  23.0   
88              15         136.0   70      110  37.1     0.153  43.0   
456              1         135.0   54        0  26.7     0.687  62.0   
200              0         113.0   80        0  31.0     0.874  21.0   
636              5         104.0   74        0  28.8     0.153  48.0   
354              3          90.0   78        0  42.7     0.559  21.0   
55               1          73.0   50        0  23.0     0.248  21.0   
522              6         114.0    0        0   0.0     0.189  26.0   
231              6         134.0   80      370  46.2     0.238  46.0   
244              2         146.0   76      194  38.2     0.329  29.0   
163              2         100.0   64        0  29.7     0.368  21.0   
141              5         106.0   82        0  39.5     0.286  38.0   
392              1         131.0   64      415  23.7     0.389  21.0   
296              2         146.0   70      360  28.0     0.337  29.0   
175              8         179.0   72      13

**4. Display the means of the features in train and test sets. Replace the null values in  __`train_df`__ and __`test_df`__  with the mean of EACH feature column separately for train and test. Display head of the dataframes.**

In [7]:
train_df.mean()




TimesPregnant      3.868098
glucoseLevel     120.798712
BP                69.269939
insulin           81.021472
BMI               31.962117
Pedigree           0.478029
Age               33.463259
IsDiabetic         0.337423
dtype: float64

In [8]:
test_df.mean()

TimesPregnant      3.715517
glucoseLevel     122.212389
BP                68.181034
insulin           72.931034
BMI               32.163793
Pedigree           0.437293
Age               32.724771
IsDiabetic         0.413793
dtype: float64

In [9]:
train_df = train_df.fillna(data.mean())
train_df.head()

TimesPregnant  glucoseLevel   BP  insulin   BMI  Pedigree   Age  \
40               3         180.0   64       70  34.0     0.271  26.0   
177              0         129.0  110      130  67.1     0.319  26.0   
600              1         108.0   88        0  27.1     0.400  24.0   
162              0         114.0   80      285  44.2     0.167  27.0   
647              0         179.0   50      159  37.8     0.455  22.0   

     IsDiabetic  
40            0  
177           1  
600           0  
162           0  
647           1

In [10]:
test_df = test_df.fillna(data.mean())
test_df.head()

TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree        Age  \
245              9         184.0  85        0  30.0     1.213  49.000000   
10               4         110.0  92        0  37.6     0.191  33.353741   
343              5         122.0  86        0  34.7     0.290  33.000000   
91               4         123.0  80      176  32.0     0.443  34.000000   
546              5         187.0  76      207  43.6     1.034  53.000000   

     IsDiabetic  
245           1  
10            0  
343           0  
91            0  
546           1

**5. Split __`train_df`__ & __`test_df`__   into  __`X_train`__, __`Y_train`__  and __`X_test`__, __`Y_test`__. __`Y_train`__  and __`Y_test`__ should only have the column we are trying to predict,  __`IsDiabetic`__.**

In [11]:
X_train = train_df.iloc[:,0:7]
Y_train = train_df.iloc[:,7]
X_test = test_df.iloc[:,0:7]
Y_test = test_df.iloc[:,7]



**6. Use this dataset to train perceptron, logistic regression and random forest models using 15% test split. Report training and test accuracies. Try different hyperparameter values for these models and see if you can improve your accuracies.**

In [12]:
# 6a. Logistic Regression
logreg = LogisticRegression()
logreg.fit(X_train, Y_train)
log_train_acc = logreg.score(X_train,Y_train)
log_test_acc = logreg.score(X_test,Y_test)

print("The training Accuracy is : ",log_train_acc)
print("The testing Accuracy is : ",log_test_acc)

The training Accuracy is :  0.7730061349693251
The testing Accuracy is :  0.7758620689655172


In [13]:
# 6b. Perceptron
percep = Perceptron()
percep.fit(X_train, Y_train)
percep_train_acc = percep.score(X_train, Y_train)
percep_test_acc = percep.score(X_test, Y_test)

print("The training Accuracy is : ",percep_train_acc)
print("The testing Accuracy is : ",percep_test_acc)


The training Accuracy is :  0.5337423312883436
The testing Accuracy is :  0.47413793103448276


In [14]:
# 6c. Random Forest
rf = RandomForestClassifier(n_estimators = 1000)
rf.fit(X_train, Y_train)
rf_train_acc = rf.score(X_train,Y_train)
rf_test_acc = rf.score(X_test, Y_test)

print("The training Accuracy is : ",rf_train_acc)
print("The testing Accuracy is : ",rf_test_acc)

The training Accuracy is :  1.0
The testing Accuracy is :  0.8017241379310345


**7. For your logistic regression model - **

**a . Compute the log probability of classes in  __`IsDiabetic`__ for the first 10 samples of your train set and display it. Also display the predicted class for those samples from your logistic regression model trained before. **


In [15]:
# Predicting the log values of the training set
logreg = LogisticRegression()
logreg.fit(X_train, Y_train)

Y_pred = logreg.predict_log_proba(X_train)
print("The log probabibility predictions are : \n",Y_pred[:10])
log2_pred = np.argmax(Y_pred,axis=1)
print(log2_pred[:10])


The log probabibility predictions are : 
 [[-1.17263406 -0.37041243]
 [-0.5913844  -0.80645117]
 [-0.10394489 -2.31541667]
 [-0.23910552 -1.54802208]
 [-1.29328009 -0.32071414]
 [-1.26832132 -0.33031604]
 [-0.3238412  -1.2850567 ]
 [-0.13322104 -2.08161673]
 [-0.24416164 -1.52952291]
 [-0.70926448 -0.67728554]]
[1 0 0 0 1 1 0 0 0 1]


**b . Now compute the log probability of classes in  __`IsDiabetic`__ for the first 10 samples of your test set and display it. Also display the predicted class for those samples from your logistic regression model trained before.
 (using the model trained on the training set)**


In [16]:
logreg = LogisticRegression()
logreg.fit(X_train, Y_train)

Y_pred2 = logreg.predict_log_proba(X_test)
print("The log probabibility predictions are : \n", Y_pred2[:10])
log2_pred_test = np.argmax(Y_pred,axis=1)
print(log2_pred_test[:10])

The log probabibility predictions are : 
 [[-1.90947637 -0.16035415]
 [-0.21779865 -1.63110784]
 [-0.33358829 -1.26000943]
 [-0.32250907 -1.28854846]
 [-2.23239337 -0.11347264]
 [-0.12618877 -2.13240729]
 [-0.58276078 -0.81724831]
 [-0.05949811 -2.85141223]
 [-0.67928537 -0.70720384]
 [-0.08234116 -2.53777222]]
[1 0 0 0 1 1 0 0 0 1]


**c . What can you interpret from the log probabilities and the predicted classes?**



In [17]:
print("From the values of the log probabilities, we can see that almost all of the values obtained are near 0, which implies that the predictions are good. The higher the value, the better. The predicted class results seems valid given the dataset.")

From the values of the log probabilities, we can see that almost all of the values obtained are near 0, which implies that the predictions are good. The higher the value, the better. The predicted class results seems valid given the dataset.


**8. Is mean imputation is the best type of imputation (as we did in 4.) to use? Why or why not? What are some other ways to impute the data?**

Your answer here

In [18]:
print("Mean imputation is not the best way to impute data as its application has many issues, the biggest being that the relations between the features are not preserved. This could result in the model showing stronger or weaker relations than what is actually present, especially if the missing data is not random. A different way to implement imputation could be to use regresssion to estimate the value and then used this prediction in the model. ")

Mean imputation is not the best way to impute data as its application has many issues, the biggest being that the relations between the features are not preserved. This could result in the model showing stronger or weaker relations than what is actually present, especially if the missing data is not random. A different way to implement imputation could be to use regresssion to estimate the value and then used this prediction in the model. 


## Extra Credit (2 pts) - MANDATORY for students enrolled in IEOR 290


**9.  Implement the K-Nearest Neighbours (https://en.wikipedia.org/wiki/K-nearest_neighbors_algorithm) algorithm for k=1 from scratch in python (do not use KNN from existing libraries). KNN uses Euclidean distance to find nearest neighbors. Split your dataset into test and train as before. Also fill in the null values with mean of features as done earlier. Use this algorithm to predict values for 'IsDiabetic' for your test set. Display your accuracy. **

In [23]:
#Creating the algorithm
from sklearn.metrics import accuracy_score
Y_pred = []*1000
Y_test = Y_train.reset_index()
for index_test, row_test in X_test.iterrows():
    distance = []
    for index_train, row_train in X_train.iterrows():
        temp_dist = np.sqrt(np.power((row_train - row_test),2).sum())
        distance.append(temp_dist)
    distance = np.array(distance)
    min_ = np.argmin(distance)
    

In [24]:
Y_pred.append(Y_train[min_])

In [25]:
k = accuracy_score(Y_test,Y_pred).round(2)
print("The accuracy using K-Nearest neighbors is : ",k)

ValueError: Found input variables with inconsistent numbers of samples: [652, 1]